<a href="https://colab.research.google.com/github/parva4/NumPyPandas/blob/main/NumpyPandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
x=42
y=73
if x<y:
  print('x<y: x is {} and y is {}'.format(x,y))
print("something else")

x<y: x is 42 and y is 73
something else


In [ ]:
words=['one','two','three','four','five']
n=0
while n<5:
  print(words[n])
  n+=1


one
two
three
four
five


In [ ]:
#for loop
words=['one','two','three','four','five']
n=0
for i in words:
  print(i)
  

one
two
three
four
five


In [ ]:
#type of a variable
x=1
print("x is {}".format(x,y))
print(type(x))

x is 1
<class 'int'>


In [ ]:
#string
x='four'
print("x is {}".format(x))
print(type(x))

x is four
<class 'str'>


In [ ]:
x='x is seven "{0:<9}" "{1:>5}"'.format(8,9) #8 spaces to the right of 8 and 4 spaces to the left of 9
print('x is {}'.format(x))
print(type(x))
#or
x=f'x is seven {}{}' #fstrings

x is x is seven "8        " "    9"
<class 'str'>


In [ ]:
x=0.1+0.1-0.3+0.1
print('x is {}'.format(x))
print(type(x))
#floating point, large number of decimals
#cannot be used for monetary calculations
#instead define 0.1 and 0.3 as decimals rather than floating point nos


x is 2.7755575615628914e-17
<class 'float'>


In [ ]:
from decimal import *
a=Decimal('0.1')
b=Decimal('0.3')
y=a+a+a-b
print(y)

0.0


In [ ]:
#bool
x=True
print('x is {}'.format(x))

x is True


In [ ]:
#nonetype
x=None
print('x is {}'.format(x))
print(type(x))

x is None
<class 'NoneType'>


In [ ]:
x=[1,2,3,4,5]
for i in x:
  #print('i is {}'.format(i))
  print(i)
print(x[3])

1
2
3
4
5
4


In [ ]:
#x=range(10)
#for i in x:
  #print(i)

x=range(5,50,5)     #range(start,end,increment)
for i in x:
  print(i)

5
10
15
20
25
30
35
40
45


In [ ]:
x=list(range(10)) #use list func if you want it to be mutable
print(x) 

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
x={'one':1,'two':2,'three':3,'four':4,'five':5}
for i,j in x.items(): #items returns a tuple pair, key and values
  print('i is {}, j is {}'.format(i,j))

i is one, j is 1
i is two, j is 2
i is three, j is 3
i is four, j is 4
i is five, j is 5


In [ ]:
x=(1,'two',3.0,['four',4],5)
y=(1,'two',3.0,['four',4],5)
print(id(x[1])) #prints identifier of variable x
print(id(y[1]))
if x[0]==y[0]:
  print("same") #since x[0] and y[0] have same equal value, python assigns them the same identifier
else:
  print("different")

same


In [ ]:
#isinstance #used to check a list or tuple
x=(1,'two',3.0,['four',4],5)
if isinstance(x,tuple):
  print("yes, a tuple")
elif isinstance(x,list):
  print("its a list")
else:
  print("nope")

yes, a tuple


In [ ]:
if True:
  print('true')
elif False:
  print('False')
else:
  print('fuckoff')

true


In [ ]:
x=3
if x==0:
  print('true')
elif x!=0:
  print('everything else')
else:
  print('f')

everything else


SyntaxError: ignored

In [ ]:
#arithmetic operators
x=3
y=2
print(f'sum is {x+y}')

sum is 5


In [ ]:
a=True
b=False
if not a:
  print('false')
else:
  print('true')

true


In [ ]:
x=['abc','xyz','pqr']
y='xyz'
if y in x[1]:
  print('present')
else:
  print('absent')
print(id(y))
print(id(x[1]))

present
140166639972016
140166639972016


In [ ]:
#input
name=input('enter your name:')
age=input('enter your age:')
print('hi!'+name+' you are'+ age)

enter your name:parv
enter your age:22
hi!parv you are22


In [ ]:
#while
secret='swordfish'
pw=''
while pw!=secret:
  pw=input('whats the code')

whats the codeabc
whats the codeswordfish


In [ ]:
#for loop
animals=['dog','cat','monkey']
for pet in animals:
  print(pet)


dog
cat
monkey


In [ ]:
secret='swordfish'
pw=''
auth=False
i=1
max=5
while pw!=secret:
  if i>max: break
  input(f'{i}:whats thhe code')
  i+=1
else:
  auth=True
print("authorized" if auth else "calling fbi..")

1:whats thhe codeabc
2:whats thhe codexxx
3:whats thhe codezzz
4:whats thhe codeyyyy
5:whats thhe codepqr
calling fbi..


In [ ]:
#for loop
animals=['dog','cat','monkey']
for pet in animals:
  if pet=='dog':continue
  if pet=='monkey':break
  print(pet)
print('thats all')

cat
thats all


In [ ]:
#functions
def Helloworld():
  print('hello world')
Helloworld()

hello world


In [ ]:
#functions
def returnadd(n1,n2):
  return(n1+n2)
sum=returnadd(12,34)
print(sum)


46


In [ ]:
#functions
def greeting(name):
  print("hi"+name+"!!")
greeting('parva')

hi	parva!!


In [ ]:
#functions cont
def main():
  kitten(3)
def kitten(n):
  print(f'{n} Meow')
#if __name__=='__main__': main()
main()

3 Meow


In [ ]:
#functions cont
def main():
  kitten(3)
def kitten(x,y=1,z=0):
  print('Meow')
  print(x,y,z)
#if __name__=='__main__': main()
main()

Meow
3 1 0


In [ ]:
#functions
def main():
  x=5
  kitten(x)
  print(f'in main: x is {x}')
def kitten(a):
  a=2
  print('Meow')
  print(a)
#if __name__=='__main__': main()
main()

Meow
2
in main: x is 5


In [ ]:
#variable argument length list
def main():
  kitten('meow','grrr','purr')
def kitten(*args):
  if len(args): #checks whether the length is greater than zero
    for s in args:
      print(s)
  else:
    print('N/A')
main()


meow
grrr
purr


In [ ]:
#functions using **kwargs
def main():
  kitten(Buffy='grrr',zilla='meow', Angel='prrr')
def kitten(**kwargs): #checks whether the length is greater than zero
  if len(kwargs):
    for s in kwargs:
      print('kitten {} says {}'.format(s,kwargs[s]))
  else:
    print('meow')
main()


kitten Buffy says grrr
kitten zilla says meow
kitten Angel says prrr


In [ ]:
x=42
print(type(x))

<class 'int'>


In [ ]:
#return values
def main():
  x=kitten()
  print(type(x),x)
def kitten():
  print('meow')
  return [42,43,444]
main()

meow
<class 'list'> [42, 43, 444]


In [ ]:
def main():
  for i in range(25):
    print(i,end=' ')
main()

0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 

In [ ]:
def main():
  for i in range(5,25,5): #initial,final,increment
    print(i,end=' ')
main()

5 10 15 20 

In [ ]:
#decorators
def f1():
  print('this is f1')
x=f1
x()

this is f1


In [ ]:
#decorators
def f1(f):
  def f2():
    print('before function call')
    f()
    print('after function call')
  return f2
def f3():
  print('hey! f3 here')
f3=f1(f3)
f3()

before function call
hey! f3 here
after function call


In [ ]:
#decorators
def f1(f):
  def f2():
    print('before function call')
    f()
    print('after function call')
  return f2
@f1 #@f1 is a decorator
def f3():
  print('hey! f3 here')
f3()

before function call
hey! f3 here
after function call


In [ ]:
def main():
  game=['gta','csgo','forza']
  print(game[1:3])
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

['csgo', 'forza']
gta 
csgo 
forza 


In [ ]:
#using index function for a list
def main():
  game=['gta','csgo','forza']
  i=game.index('csgo')
  print(game[i])
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

csgo
gta 
csgo 
forza 


In [ ]:
#using append
def main():
  game=['gta','csgo','forza']
  game.append('contra') #append adds a new element to the list
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

gta 
csgo 
forza 
contra 


In [ ]:
#using insert function
def main():
  game=['gta','csgo','forza']
  game.insert(0,'contra') #inserts a new element at position zero
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

contra 
gta 
csgo 
forza 


In [ ]:
#remove function
def main():
  game=['gta','csgo','forza']
  game.remove('csgo') #removes csgo from the list game
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

gta 
forza 


In [ ]:
#pop
def main():
  game=['gta','csgo','forza']
  game.pop() #removes last element from the list game
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

gta 
csgo 


In [ ]:
#join
def main():
  game=['gta','csgo','forza']
  print(', '.join(game)) #prints the list with the elements separated by a comma
  print_list(game)
def print_list(list):
  for i in list:
    print(i,end=' \n')
main()

gta, csgo, forza
gta 
csgo 
forza 


In [ ]:
#dictionary
def main():
  animals=dict(kitten='meow',dog='bhow',dragon='boom')
  print(animals['kitten'])
  print_dict(animals)
def print_dict(dictionary):
  for k,v in dictionary.items():
    print(f'{k}:{v}')
main()


meow
kitten:meow
dog:bhow
dragon:boom


In [ ]:
#sets
def main():
  a=set('we will need a bigger boat')
  b=set('i am afraid of that') #a|b is the 'or' operator
  print_set(a&b) #a-b prints elements of a that are not in b
def print_set(o): #a&b is the intersection, prints common elements 
  print('{',end='')
  for x in o:
    print(x,end='')
  print('}')
main()

{taro di}


In [ ]:
#list comprehension
def main():
  seq=range(11)
  seq2=[x*2 for x in seq]
  print_list(seq)
  print('\t')
  print_list(seq2)
def print_list(o):
  for x in o:
    print(x,end=' ')
    print()
main()


0 
1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
	
0 
2 
4 
6 
8 
10 
12 
14 
16 
18 
20 


In [ ]:
#list comprehension
def main():
  seq=range(11)
  seq2=[(x,x**2) for x in seq]
  print_list(seq)
  print('\t')
  print_list(seq2)
def print_list(o):
  for x in o:
    print(x,end=' ')
    print()
main()

0 
1 
2 
3 
4 
5 
6 
7 
8 
9 
10 
	
(0, 0) 
(1, 1) 
(2, 4) 
(3, 9) 
(4, 16) 
(5, 25) 
(6, 36) 
(7, 49) 
(8, 64) 
(9, 81) 
(10, 100) 


In [ ]:
#list comprehension
def main():
  seq=range(11)
  from math import pi
  seq2=[round(pi,i) for i in seq] #rounds pi with 'i' number of decimals
  print_list(seq)
  print('\t')
  print_list(seq2)
def print_list(o):
  for x in o:
    print(x,end=' ')
main()

0 1 2 3 4 5 6 7 8 9 10 	
3.0 3.1 3.14 3.142 3.1416 3.14159 3.141593 3.1415927 3.14159265 3.141592654 3.1415926536 

In [ ]:
#list comprehension
def main():
  seq=range(11)
  seq2={x:x**2 for i in seq} #rounds pi with 'i' number of decimals
  print_list(seq)
  print('\t')
  print_list(seq2)
def print_list(o):
  for x in o:
    print(x,end=' ')
main()

0 1 2 3 4 5 6 7 8 9 10 	
2 

In [ ]:
def main():
  r=range(11)
  l=[1,'two',3,{'4:''four'},5]
  t=('one','two',None,'four','five')
  s=set('its a bird! its a superman')
  d=dict(one=r,two=l,three=s)
  mixed=[l,r,s,d,t]
  disp(mixed)


In [ ]:
class robot:
  def instance_self(self):
    print("my name is "+self.name)
r1=robot()
r1.name="tom"
r1.color="gray"
r1.weight=30
r1.instance_self()

my name is tom


In [ ]:
#using __init__
class robot:
  def __init__(self,name,color,weight):
    self.name=name
    self.color=color
    self.weight=weight
  def instance_self(self):
    print("my name is "+self.name)
r1=robot("tom","grey",30)
r2=robot("jerry","red",10)
r1.instance_self()
r2.instance_self()

my name is tom
my name is jerry


In [ ]:
class person:
  def __init__(self,n,p,i):
    self.name=n
    self.personality=p
    self.issittting=i
  def sit_down(self):
    self.issitting=True
  def stand(self):
    self.issitting=False
p1=person("alice","aggressive",False)
p2=person("lyka","calm",True)

class robot:
  def __init__(self,name,color,weight):
    self.name=name
    self.color=color
    self.weight=weight
  def instance_self(self):
    print("my name is "+self.name)
r1=robot("tom","grey",30)
r2=robot("jerry","red",10)

p1.robot_owned=r2
p2.robot_owned=r1

p1.robot_owned.instance_self()
p2.robot_owned.instance_self()

my name is jerry
my name is tom


In [ ]:
#handling exceptions
def main():
  try:
    x=int('shoo') #shoo is a string, not an integer
  except ValueError:
    print('got a valueerror')
main()

got a valueerror


In [ ]:
#handling exceptions
def main():
  try:
    x=5/3
  except ValueError:
    print('got a valueerror')
  except:
    print(f'unknkown error: {sys.exc_info()}')
  else:
    print('great! no error reported')
    print(x)
main()

great! no error reported
1.6666666666666667


In [ ]:
def inclusive_range(*args):
  numargs=len(args)
  start=0
  step=1
  if numargs<1:
    raise TypeError(f'expected atleast one arg, got {numargs}')
  elif numargs==1:
    stop=args[0]
  elif numargs==2:
    (start,stop)=args
  elif numargs==3:
    (start,stop,step)=args
  else:
    raise TypeError(f'expected atmost 3 args, got {numargs}')
  i=start
  while i<=stop:
    yield i
    i+=step
def main():
  for i in inclusive_range():
    print(i,end=' ')
main()

TypeError: ignored

In [ ]:
#strings
print('Hello World'.swapcase()) #swapcase swaps the cases of the letters in the string

hELLO wORLD


In [ ]:
#strings
print(f'Hello World {42*7}')

Hello World 294


In [ ]:
class MyString(str):
  def __str__(self): 
    return self[::-1] #-1 prints the string backwards
s=MyString('Hello, world!')
print(s)

!dlrow ,olleH


In [ ]:
print('hello world'.capitalize()) #capitalizes the first letters of each word

Hello world


In [ ]:
print('hello world'.upper())

HELLO WORLD


In [ ]:
print('hello world'.casefold())

hello world


In [ ]:
s1='hello world'
s2=s1.upper()
print(id(s1))
print(id(s2))

140048279533872
140048279555888


In [ ]:
s1='hello world,'
s2='another string'
print(s1+' '+s2)

hello world, another string


In [ ]:
x=42
y=73
print('x and y are {0:<5} {1:>6}'.format(x,y))

x and y are 42        73


In [ ]:
x=42*900
print(f'the number is {x:0.1f}')

the number is 37800.0


In [ ]:
s='this is a long sentence whichh cannot fit in a single line'
l=s.split()
s2='--'.join((l))
print(s2)

this--is--a--long--sentence--whichh--cannot--fit--in--a--single--line


In [ ]:
#opening files
def main():
  f=open('lines.txt')
  for line in f:
    print(line.rstrip())
main()

FileNotFoundError: ignored

In [ ]:
with open('lines.txt',"r") as f: #mention only the file name if both .py and .txt file are in the same folder, else mention the path of the text file
    f_contents=f.read() 
    print(f_contents)

In [ ]:
#numpy
import numpy as np
a=np.array([1,2,3])
b=np.array([[1.0,2.0,3,0],[4.0,5.0,6.0]])
print(a)
print(b)
a.ndim #dimension of the numpy array
b.dtype #data type
a.size #size of array
b.shape

[1 2 3]
[list([1.0, 2.0, 3, 0]) list([4.0, 5.0, 6.0])]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  after removing the cwd from sys.path.


(2,)

In [ ]:
#numpy
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) #2 x 7 array
a[0,4] #row 0 column 4

5

In [ ]:
#numpy
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]]) #2 x 6 array
a[0,:] #prints row 0 all columns

array([1, 2, 3, 4, 5, 6])

In [ ]:
a[0,1:-1:2]

array([2, 4])

In [ ]:
a[1,5]=20
a[:,2]=[1,2] #column 2 has 1,2
print(a)

[[ 1  2  1  4  5  6]
 [ 7  8  2 10 11 20]]


In [ ]:
import numpy as np
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[1,0,0] #prints 8 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


5

In [ ]:
#zero vector using np
np.zeros(5)

NameError: ignored

In [ ]:
import numpy as np
np.full((3,2,2),99,dtype='int') #prints 3*2x2 matrix of 99 having a float datatype

array([[[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99]]])

In [ ]:
import numpy as np
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
np.full(a.shape,4) #or np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4]])

In [ ]:
#random decimal numbers
a=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
np.random.random_sample(a.shape)

array([[0.17461412, 0.74370289, 0.8972108 , 0.94910614, 0.31495107,
        0.30010247],
       [0.06134896, 0.74507828, 0.11396251, 0.08509748, 0.83568917,
        0.82630628]])

In [ ]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#random integer values
a=np.random.randint((-5,6),size=(3,2))

ValueError: ignored

In [ ]:
arr=np.array([[1,2,3]])
np.repeat(arr,2,axis=0)

array([[1, 2, 3],
       [1, 2, 3]])

In [ ]:
import numpy as np
a=np.ones((5,5))
print(a)
b=np.zeros((3,3))
b[1,1]=9
print(b)
a[1:-1,1:-1]=b
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
a=np.array([1,2,3])
b=a.copy()
print(b)

[1 2 3]


In [ ]:
a=np.ones((2,3))
print(a)
b=np.full((3,2),2) #(3,2) is the matrix dimension, 2 is the value
print(b)
np.matmul(a,b) #matrix multiplication of a and b

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
import numpy as np
c=np.identity(3)
np.linalg.det(c) #finds determinant of matrix 

1.0

In [ ]:
stats=np.array([[1,2,3],[4,5,6]])
np.min(stats)

1

In [ ]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after=before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
np.vstack([a,b])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
import numpy as np
np.genfromtxt('/data1.txt',delimiter=',')

FileNotFoundError: ignored

Pandas

In [ ]:
import pandas as pd
pd.read_csv('/olympics.csv')

In [ ]:
import pandas as pd
pd.read_csv('/data.txt')

1   2   3   4
0   5   6   7   8
1   9  10  11  12
2  13  14  15  16

In [ ]:
import pandas as pd
file=pd.read_csv('/olympics.txt')


ParserError: ignored

In [ ]:
import pandas as pd
df=pd.read_csv('pokemon_data.csv')
print(df.columns)
print(df['Name'])

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')
0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object


In [ ]:
import pandas as pd
df=pd.read_csv('pokemon_data.csv')
#df.columns
#print(df.iloc[0:4]) #reads each row
#print(df.iloc[4,1]) #prints the element in 4th row 1st column
# for index,row in df.iterrows():
  #print(index,row)
#df.loc[df['Type 1']=='Fire'] #prints every row where Type 1=Fire
#df.describe()
#df.sort_values(['Name'])
#df.sort_values('Name',ascending=False)
df.sort_values(['Type 1','HP'],ascending=False)

#       Name Type 1  Type 2  ...  Sp. Def  Speed  Generation  Legendary
351  321    Wailord  Water     NaN  ...       45     60           3      False
655  594  Alomomola  Water     NaN  ...       45     65           5      False
142  131     Lapras  Water     Ice  ...       95     60           1      False
145  134   Vaporeon  Water     NaN  ...       95     65           1      False
350  320    Wailmer  Water     NaN  ...       35     60           3      False
..   ...        ...    ...     ...  ...      ...    ...         ...        ...
314  290    Nincada    Bug  Ground  ...       30     40           3      False
462  415     Combee    Bug  Flying  ...       42     70           4      False
603  543   Venipede    Bug  Poison  ...       39     57           5      False
230  213    Shuckle    Bug    Rock  ...      230      5           2      False
316  292   Shedinja    Bug   Ghost  ...       30     40           3      False

[800 rows x 12 columns]

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
print(data)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80   

In [ ]:
import pandas as pd
data=pd.read_excel('pokemon_data.xlsx')
print(data)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80   

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.txt',delimiter='\t')
print(data)

       #                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80   

In [ ]:
#getting columns out of a table
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#print(data['Name'][0:5])
print(data.Name)

0                  Bulbasaur
1                    Ivysaur
2                   Venusaur
3      VenusaurMega Venusaur
4                 Charmander
               ...          
795                  Diancie
796      DiancieMega Diancie
797      HoopaHoopa Confined
798       HoopaHoopa Unbound
799                Volcanion
Name: Name, Length: 800, dtype: object


In [ ]:
#iloc=integer location, used say when you want to print a row
import pandas as pd
df=pd.read_csv('pokemon_data.csv')
print(df.iloc[1]) #printing a cell from 2nd row 1st column
#print(df.iloc[2,1])

#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object


In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#for index,row in data.iterrows():
  #print(index,row)
data.loc[data['Type 1']=="Fire"]

#                       Name Type 1    Type 2   HP  Attack  Defense  \
4      4                 Charmander   Fire       NaN   39      52       43   
5      5                 Charmeleon   Fire       NaN   58      64       58   
6      6                  Charizard   Fire    Flying   78      84       78   
7      6  CharizardMega Charizard X   Fire    Dragon   78     130      111   
8      6  CharizardMega Charizard Y   Fire    Flying   78     104       78   
42    37                     Vulpix   Fire       NaN   38      41       40   
43    38                  Ninetales   Fire       NaN   73      76       75   
63    58                  Growlithe   Fire       NaN   55      70       45   
64    59                   Arcanine   Fire       NaN   90     110       80   
83    77                     Ponyta   Fire       NaN   50      85       55   
84    78                   Rapidash   Fire       NaN   65     100       70   
135  126                     Magmar   Fire       NaN   65      95       57   
147  136                    Flareon   Fire       NaN   65     130       60   
158  146                    Moltres   Fire    Flying   90     100       90   
169  155                  Cyndaquil   Fire       NaN   39      52       43   
170  156                    Quilava   Fire       NaN   58      64       58   
171  157                 Typhlosion   Fire       NaN   78      84       78   
236  218                     Slugma   Fire       NaN   40      40       40   
237  219                   Magcargo   Fire      Rock   50      50      120   
259  240                      Magby   Fire       NaN   45      75       37   
263  244                      Entei   Fire       NaN  115     115       85   
270  250                      Ho-oh   Fire    Flying  106     130       90   
276  255                    Torchic   Fire       NaN   45      60       40   
277  256                  Combusken   Fire  Fighting   60      85       60   
278  257                   Blaziken   Fire  Fighting   80     120       70   
279  257      BlazikenMega Blaziken   Fire  Fighting   80     160       80   
352  322                      Numel   Fire    Ground   60      60       40   
353  323                   Camerupt   Fire    Ground   70     100       70   
354  323      CameruptMega Camerupt   Fire    Ground   70     120      100   
355  324                    Torkoal   Fire       NaN   70      85      140   
435  390                   Chimchar   Fire       NaN   44      58       44   
436  391                   Monferno   Fire  Fighting   64      78       52   
437  392                  Infernape   Fire  Fighting   76     104       71   
518  467                  Magmortar   Fire       NaN   75      95       67   
542  485                    Heatran   Fire     Steel   91      90      106   
557  498                      Tepig   Fire       NaN   65      63       45   
558  499                    Pignite   Fire  Fighting   90      93       55   
559  500                     Emboar   Fire  Fighting  110     123       65   
572  513                    Pansear   Fire       NaN   50      53       48   
573  514                   Simisear   Fire       NaN   75      98       63   
614  554                   Darumaka   Fire       NaN   70      90       45   
615  555    DarmanitanStandard Mode   Fire       NaN  105     140       55   
616  555         DarmanitanZen Mode   Fire   Psychic  105      30      105   
692  631                    Heatmor   Fire       NaN   85      97       66   
721  653                   Fennekin   Fire       NaN   40      45       40   
722  654                    Braixen   Fire       NaN   59      59       58   
723  655                    Delphox   Fire   Psychic   75      69       72   
730  662                Fletchinder   Fire    Flying   62      73       55   
731  663                 Talonflame   Fire    Flying   78      81       71   
735  667                     Litleo   Fire    Normal   62      50       58   
736  668                     

In [ ]:
#sorting values
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.sort_values(['Type 1','HP'],ascending=[1,0]) #sorts Type 1 in ascending, HP in descending

#                     Name Type 1    Type 2  HP  Attack  Defense  \
520  469                  Yanmega    Bug    Flying  86      76       86   
698  637                Volcarona    Bug      Fire  85      60       65   
231  214                Heracross    Bug  Fighting  80     125       75   
232  214  HeracrossMega Heracross    Bug  Fighting  80     185      115   
678  617                 Accelgor    Bug       NaN  80      70       40   
..   ...                      ...    ...       ...  ..     ...      ...   
106   98                   Krabby  Water       NaN  30     105       90   
125  116                   Horsea  Water       NaN  30      40       70   
129  120                   Staryu  Water       NaN  30      45       55   
139  129                 Magikarp  Water       NaN  20      10       55   
381  349                   Feebas  Water       NaN  20      15       20   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
520      116       56     95           4      False  
698      135      105    100           5      False  
231       40       95     85           2      False  
232       40      105     75           2      False  
678      100       60    145           5      False  
..       ...      ...    ...         ...        ...  
106       25       25     50           1      False  
125       70       25     60           1      False  
129       70       55     85           1      False  
139       15       20     80           1      False  
381       10       55     80           3      False  

[800 rows x 12 columns]

In [ ]:
#adding a new column that depends on other columns
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data['Total']=data['Attack' ]+data['Defense']+data['HP']+data['Sp. Atk']+data['Sp. Def']+data['Speed']
p=data.head(5)
p.sort_values(['Total'],ascending=False)
#dropping 'Total' column
data.drop(columns=['Total'])

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [ ]:
#another way of adding column values
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data['Total']=data.iloc[:,4:9].sum(axis=1) #all rows,columns 4 to 9
data.head(3)

#       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45   
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60   
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80   

   Generation  Legendary  Total  
0           1      False    273  
1           1      False    345  
2           1      False    445

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data['Total']=data.iloc[:,4:10].sum(axis=1)
cols=list(data.columns)
data=data[cols[0:5]+[cols[-1]]+cols[5:12]]
data.to_csv('modified.csv',index=False) #will not include index in the csv

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.to_csv('mod.txt',index=False,sep='\t')

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.loc[(data['Type 1']=='Grass') | (data['Type 2']=='Poison')]

#                   Name Type 1    Type 2   HP  Attack  Defense  \
0      1              Bulbasaur  Grass    Poison   45      49       49   
1      2                Ivysaur  Grass    Poison   60      62       63   
2      3               Venusaur  Grass    Poison   80      82       83   
3      3  VenusaurMega Venusaur  Grass    Poison   80     100      123   
16    13                 Weedle    Bug    Poison   40      35       30   
..   ...                    ...    ...       ...  ...     ...      ...   
718  650                Chespin  Grass       NaN   56      61       65   
719  651              Quilladin  Grass       NaN   61      78       95   
720  652             Chesnaught  Grass  Fighting   88     107      122   
740  672                 Skiddo  Grass       NaN   66      65       48   
741  673                 Gogoat  Grass       NaN  123     100       62   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
16        20       20     50           1      False  
..       ...      ...    ...         ...        ...  
718       48       45     38           6      False  
719       56       58     57           6      False  
720       74       75     64           6      False  
740       62       57     52           6      False  
741       97       81     68           6      False  

[89 rows x 12 columns]

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.loc[(data['Type 1']=='Grass') & (data['Type 2']=='Poison')]

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65   
1      2                Ivysaur  Grass  Poison   60      62       63       80   
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
48    43                 Oddish  Grass  Poison   45      50       55       75   
49    44                  Gloom  Grass  Poison   60      65       70       85   
50    45              Vileplume  Grass  Poison   75      80       85      110   
75    69             Bellsprout  Grass  Poison   50      75       35       70   
76    70             Weepinbell  Grass  Poison   65      90       50       85   
77    71             Victreebel  Grass  Poison   80     105       65      100   
344  315                Roselia  Grass  Poison   50      60       45      100   
451  406                  Budew  Grass  Poison   40      30       35       50   
452  407               Roserade  Grass  Poison   60      70       65      125   
651  590                Foongus  Grass  Poison   69      55       45       55   
652  591              Amoonguss  Grass  Poison  114      85       70       85   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
3        120     80           1      False  
48        65     30           1      False  
49        75     40           1      False  
50        90     50           1      False  
75        30     40           1      False  
76        45     55           1      False  
77        70     70           1      False  
344       80     65           3      False  
451       70     55           4      False  
452      105     90           4      False  
651       55     15           5      False  
652       80     30           5      False

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
new_df=data.loc[(data['Type 1']=='Grass') & (data['Type 2']=='Poison')]
new_df=new_df.reset_index(drop=True)
new_df

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0     1              Bulbasaur  Grass  Poison   45      49       49       65   
1     2                Ivysaur  Grass  Poison   60      62       63       80   
2     3               Venusaur  Grass  Poison   80      82       83      100   
3     3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
4    43                 Oddish  Grass  Poison   45      50       55       75   
5    44                  Gloom  Grass  Poison   60      65       70       85   
6    45              Vileplume  Grass  Poison   75      80       85      110   
7    69             Bellsprout  Grass  Poison   50      75       35       70   
8    70             Weepinbell  Grass  Poison   65      90       50       85   
9    71             Victreebel  Grass  Poison   80     105       65      100   
10  315                Roselia  Grass  Poison   50      60       45      100   
11  406                  Budew  Grass  Poison   40      30       35       50   
12  407               Roserade  Grass  Poison   60      70       65      125   
13  590                Foongus  Grass  Poison   69      55       45       55   
14  591              Amoonguss  Grass  Poison  114      85       70       85   

    Sp. Def  Speed  Generation  Legendary  
0        65     45           1      False  
1        80     60           1      False  
2       100     80           1      False  
3       120     80           1      False  
4        65     30           1      False  
5        75     40           1      False  
6        90     50           1      False  
7        30     40           1      False  
8        45     55           1      False  
9        70     70           1      False  
10       80     65           3      False  
11       70     55           4      False  
12      105     90           4      False  
13       55     15           5      False  
14       80     30           5      False

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.loc[(data['Name'].str.contains('Mega'))]

#                       Name    Type 1    Type 2   HP  Attack  Defense  \
3      3      VenusaurMega Venusaur     Grass    Poison   80     100      123   
7      6  CharizardMega Charizard X      Fire    Dragon   78     130      111   
8      6  CharizardMega Charizard Y      Fire    Flying   78     104       78   
12     9    BlastoiseMega Blastoise     Water       NaN   79     103      120   
19    15      BeedrillMega Beedrill       Bug    Poison   65     150       40   
23    18        PidgeotMega Pidgeot    Normal    Flying   83      80       80   
71    65      AlakazamMega Alakazam   Psychic       NaN   55      50       65   
87    80        SlowbroMega Slowbro     Water   Psychic   95      75      180   
102   94          GengarMega Gengar     Ghost    Poison   60      65       80   
124  115  KangaskhanMega Kangaskhan    Normal       NaN  105     125      100   
137  127          PinsirMega Pinsir       Bug    Flying   65     155      120   
141  130      GyaradosMega Gyarados     Water      Dark   95     155      109   
154  142  AerodactylMega Aerodactyl      Rock    Flying   80     135       85   
163  150        MewtwoMega Mewtwo X   Psychic  Fighting  106     190      100   
164  150        MewtwoMega Mewtwo Y   Psychic       NaN  106     150       70   
168  154                   Meganium     Grass       NaN   80      82      100   
196  181      AmpharosMega Ampharos  Electric    Dragon   90      95      105   
224  208        SteelixMega Steelix     Steel    Ground   75     125      230   
229  212          ScizorMega Scizor       Bug     Steel   70     150      140   
232  214    HeracrossMega Heracross       Bug  Fighting   80     185      115   
248  229      HoundoomMega Houndoom      Dark      Fire   75      90       90   
268  248    TyranitarMega Tyranitar      Rock      Dark  100     164      150   
275  254      SceptileMega Sceptile     Grass    Dragon   70     110       75   
279  257      BlazikenMega Blaziken      Fire  Fighting   80     160       80   
283  260      SwampertMega Swampert     Water    Ground  100     150      110   
306  282    GardevoirMega Gardevoir   Psychic     Fairy   68      85       65   
327  302        SableyeMega Sableye      Dark     Ghost   50      85      125   
329  303          MawileMega Mawile     Steel     Fairy   50     105      125   
333  306          AggronMega Aggron     Steel       NaN   70     140      230   
336  308      MedichamMega Medicham  Fighting   Psychic   60     100       85   
339  310    ManectricMega Manectric  Electric       NaN   70      75       80   
349  319      SharpedoMega Sharpedo     Water      Dark   70     140       70   
354  323      CameruptMega Camerupt      Fire    Ground   70     120      100   
366  334        AltariaMega Altaria    Dragon     Fairy   75     110      110   
387  354        BanetteMega Banette     Ghost       NaN   64     165       75   
393  359            AbsolMega Absol      Dark       NaN   65     150       60   
397  362          GlalieMega Glalie       Ice       NaN   80     120       80   
409  373    SalamenceMega Salamence    Dragon    Flying   95     145      130   
413  376    MetagrossMega Metagross     Steel   Psychic   80     145      150   
418  380          LatiasMega Latias    Dragon   Psychic   80     100      120   
420  381          LatiosMega Latios    Dragon   Psychic   80     130      100   
426  384      RayquazaMega Rayquaza    Dragon    Flying  105     180      100   
476  428        LopunnyMega Lopunny    Normal  Fighting   65     136       94   
494  445      GarchompMega Garchomp    Dragon    Ground  108     170      115   
498  448        LucarioMega Lucario  Fighting     Steel   70     145       88   
511  460    AbomasnowMega Abomasnow     Grass       Ice   90     132      105   
527  475        GalladeMega Gallade   Psychic  Fighting   68     165       95   
591  531          AudinoMega Audino    Normal     Fairy  103      60      126   
796  719        DiancieMega Diancie   

In [ ]:
#does not contain mega
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.loc[~(data['Name'].str.contains('Mega'))]

#                 Name   Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1            Bulbasaur    Grass  Poison   45      49       49       65   
1      2              Ivysaur    Grass  Poison   60      62       63       80   
2      3             Venusaur    Grass  Poison   80      82       83      100   
4      4           Charmander     Fire     NaN   39      52       43       60   
5      5           Charmeleon     Fire     NaN   58      64       58       80   
..   ...                  ...      ...     ...  ...     ...      ...      ...   
794  718     Zygarde50% Forme   Dragon  Ground  108     100      121       81   
795  719              Diancie     Rock   Fairy   50     100      150      100   
797  720  HoopaHoopa Confined  Psychic   Ghost   80     110       60      150   
798  720   HoopaHoopa Unbound  Psychic    Dark   80     160       60      170   
799  721            Volcanion     Fire   Water   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
4         50     65           1      False  
5         65     80           1      False  
..       ...    ...         ...        ...  
794       95     95           6       True  
795      150     50           6       True  
797      130     70           6       True  
798      130     80           6       True  
799       90     70           6       True  

[751 rows x 12 columns]

In [ ]:
import pandas as pd
import re #brings in the regex module
data=pd.read_csv('pokemon_data.csv')
data.loc[data['Type 1'].str.contains('fire|grass',flags=re.I,regex=True)]

#                   Name Type 1  Type 2   HP  Attack  Defense  Sp. Atk  \
0      1              Bulbasaur  Grass  Poison   45      49       49       65   
1      2                Ivysaur  Grass  Poison   60      62       63       80   
2      3               Venusaur  Grass  Poison   80      82       83      100   
3      3  VenusaurMega Venusaur  Grass  Poison   80     100      123      122   
4      4             Charmander   Fire     NaN   39      52       43       60   
..   ...                    ...    ...     ...  ...     ...      ...      ...   
735  667                 Litleo   Fire  Normal   62      50       58       73   
736  668                 Pyroar   Fire  Normal   86      68       72      109   
740  672                 Skiddo  Grass     NaN   66      65       48       62   
741  673                 Gogoat  Grass     NaN  123     100       62       97   
799  721              Volcanion   Fire   Water   80     110      120      130   

     Sp. Def  Speed  Generation  Legendary  
0         65     45           1      False  
1         80     60           1      False  
2        100     80           1      False  
3        120     80           1      False  
4         50     65           1      False  
..       ...    ...         ...        ...  
735       54     72           6      False  
736       66    106           6      False  
740       57     52           6      False  
741       81     68           6      False  
799       90     70           6       True  

[122 rows x 12 columns]

In [ ]:
import pandas as pd
import re
data=pd.read_csv('pokemon_data.csv')
data.loc[data['Name'].str.contains('^pi[a-z]*',flags=re.I,regex=True)]

#                 Name    Type 1    Type 2   HP  Attack  Defense  \
20    16               Pidgey    Normal    Flying   40      45       40   
21    17            Pidgeotto    Normal    Flying   63      60       55   
22    18              Pidgeot    Normal    Flying   83      80       75   
23    18  PidgeotMega Pidgeot    Normal    Flying   83      80       80   
30    25              Pikachu  Electric       NaN   35      55       40   
136  127               Pinsir       Bug       NaN   65     125      100   
137  127    PinsirMega Pinsir       Bug    Flying   65     155      120   
186  172                Pichu  Electric       NaN   20      40       15   
219  204               Pineco       Bug       NaN   50      65       90   
239  221            Piloswine       Ice    Ground  100     100       80   
438  393               Piplup     Water       NaN   53      51       53   
558  499              Pignite      Fire  Fighting   90      93       55   
578  519               Pidove    Normal    Flying   50      55       50   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
20        35       35     56           1      False  
21        50       50     71           1      False  
22        70       70    101           1      False  
23       135       80    121           1      False  
30        50       50     90           1      False  
136       55       70     85           1      False  
137       65       90    105           1      False  
186       35       35     60           2      False  
219       35       35     15           2      False  
239       60       60     50           2      False  
438       61       56     40           4      False  
558       70       55     55           5      False  
578       36       30     43           5      False

Conditional Changes in Pandas

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data['Total']=data.iloc[:,4:9].sum(axis=1)
data.loc[data['Total']>500,['Generation','Legendary']]='TestVal'
data

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed Generation Legendary  Total  
0         65       65     45          1     False    273  
1         80       80     60          1     False    345  
2        100      100     80          1     False    445  
3        122      120     80    TestVal   TestVal    545  
4         60       50     65          1     False    244  
..       ...      ...    ...        ...       ...    ...  
795      100      150     50    TestVal   TestVal    550  
796      160      110    110    TestVal   TestVal    590  
797      150      130     70    TestVal   TestVal    530  
798      170      130     80    TestVal   TestVal    600  
799      130       90     70    TestVal   TestVal    530  

[800 rows x 13 columns]

Pandas aggregate statistics (group by)

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
data.groupby(data['Type 1']).mean().sort_values('Defense',ascending=False)

#         HP      Attack     Defense    Sp. Atk    Sp. Def  \
Type 1                                                                          
Steel     442.851852  65.222222   92.703704  126.370370  67.518519  80.629630   
Rock      392.727273  65.363636   92.863636  100.795455  63.340909  75.477273   
Dragon    474.375000  83.312500  112.125000   86.375000  96.843750  88.843750   
Ground    356.281250  73.781250   95.750000   84.843750  56.468750  62.750000   
Ghost     486.500000  64.437500   73.781250   81.187500  79.343750  76.468750   
Water     303.089286  72.062500   74.151786   72.946429  74.812500  70.517857   
Ice       423.541667  72.000000   72.750000   71.416667  77.541667  76.291667   
Grass     344.871429  67.271429   73.214286   70.800000  77.500000  70.428571   
Bug       334.492754  56.884058   70.971014   70.724638  53.869565  64.797101   
Dark      461.354839  66.806452   88.387097   70.225806  74.645161  69.516129   
Poison    251.785714  67.250000   74.678571   68.821429  60.428571  64.392857   
Fire      327.403846  69.903846   84.769231   67.769231  88.980769  72.211538   
Psychic   380.807018  70.631579   71.456140   67.684211  98.403509  86.280702   
Electric  363.500000  59.795455   69.090909   66.295455  90.022727  73.704545   
Flying    677.750000  70.750000   78.750000   66.250000  94.250000  72.500000   
Fighting  363.851852  69.851852   96.777778   65.925926  53.111111  64.703704   
Fairy     449.529412  74.117647   61.529412   65.705882  78.529412  84.705882   
Normal    319.173469  77.275510   73.469388   59.846939  55.816327  63.724490   

               Speed  Generation  Legendary  
Type 1                                       
Steel      55.259259    3.851852   0.148148  
Rock       55.909091    3.454545   0.090909  
Dragon     83.031250    3.875000   0.375000  
Ground     63.906250    3.156250   0.125000  
Ghost      64.343750    4.187500   0.062500  
Water      65.964286    2.857143   0.035714  
Ice        63.458333    3.541667   0.083333  
Grass      61.928571    3.357143   0.042857  
Bug        61.681159    3.217391   0.000000  
Dark       76.161290    4.032258   0.064516  
Poison     63.571429    2.535714   0.000000  
Fire       74.442308    3.211538   0.096154  
Psychic    81.491228    3.385965   0.245614  
Electric   84.500000    3.272727   0.090909  
Flying    102.500000    5.500000   0.500000  
Fighting   66.074074    3.370370   0.000000  
Fairy      48.588235    4.117647   0.058824  
Normal     71.551020    3.051020   0.020408

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#data.groupby(data['Type 1']).sum().sort_values('Defense',ascending=False)
data.groupby(data['Type 1']).count()

#  Name  Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
Type 1                                                                       
Bug        69    69      52   69      69       69       69       69     69   
Dark       31    31      21   31      31       31       31       31     31   
Dragon     32    32      21   32      32       32       32       32     32   
Electric   44    44      17   44      44       44       44       44     44   
Fairy      17    17       2   17      17       17       17       17     17   
Fighting   27    27       7   27      27       27       27       27     27   
Fire       52    52      24   52      52       52       52       52     52   
Flying      4     4       2    4       4        4        4        4      4   
Ghost      32    32      22   32      32       32       32       32     32   
Grass      70    70      37   70      70       70       70       70     70   
Ground     32    32      19   32      32       32       32       32     32   
Ice        24    24      11   24      24       24       24       24     24   
Normal     98    98      37   98      98       98       98       98     98   
Poison     28    28      13   28      28       28       28       28     28   
Psychic    57    57      19   57      57       57       57       57     57   
Rock       44    44      35   44      44       44       44       44     44   
Steel      27    27      22   27      27       27       27       27     27   
Water     112   112      53  112     112      112      112      112    112   

          Generation  Legendary  
Type 1                           
Bug               69         69  
Dark              31         31  
Dragon            32         32  
Electric          44         44  
Fairy             17         17  
Fighting          27         27  
Fire              52         52  
Flying             4          4  
Ghost             32         32  
Grass             70         70  
Ground            32         32  
Ice               24         24  
Normal            98         98  
Poison            28         28  
Psychic           57         57  
Rock              44         44  
Steel             27         27  
Water            112        112

Working with large datasets specifying chunksize

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv',chunksize=3)
for data in pd.read_csv('pokemon_data.csv',chunksize=3):
  print("chunk n")
  print(data)

chunk n
   #       Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  \
0  1  Bulbasaur  Grass  Poison  45      49       49       65       65     45   
1  2    Ivysaur  Grass  Poison  60      62       63       80       80     60   
2  3   Venusaur  Grass  Poison  80      82       83      100      100     80   

   Generation  Legendary  
0           1      False  
1           1      False  
2           1      False  
chunk n
   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   
5  5             Charmeleon   Fire     NaN  58      64       58       80   

   Sp. Def  Speed  Generation  Legendary  
3      120     80           1      False  
4       50     65           1      False  
5       65     80           1      False  
chunk n
   #                       Name Type 1  Type 2  HP  Attack  Defense  S

Numpy

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([[1,2,3],[4,5,6]])
#print(a)
b.ndim #dimension of b, 2 dimensional
b.shape #2 rows 3 columns
#getting data type of array
a.dtype
b.itemsize #prints size in bits

8

In [ ]:
#editing a specific element
import numpy as np
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
#a[1,0]=20 #sets 2nd row 1st element as 20
#accessing multiple elements
a[0,1:6:2]

array([2, 4, 6])

3d example

In [ ]:
import numpy as np
a=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
a[:,0,:]

array([[1, 2],
       [5, 6]])

In [ ]:
import numpy as np
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
import numpy as np
a=np.full((2,2),99,dtype='float')
np.full_like(a,4)

array([[4., 4.],
       [4., 4.]])

In [ ]:
#random
x=np.random.rand(2,2)
x

array([[0.08686558, 0.02987929],
       [0.70723935, 0.05443101]])

In [ ]:
import numpy as np
np.random.randint(10,size=(3,3)) #prints a 3x3 matrix of random numbers less than 10
#printing identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
r=np.repeat(a,3,axis=0)
print(r)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
r=np.repeat(a,1,axis=0)
print(r)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
op=np.ones((5,5))
print(op)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
x=np.ones((5,5))
x[1:-1,1:-1]=0
x[2,2]=9
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
#copying the contents of one array into another
a=np.array([1,2,3])
a[1]=100
b=a.copy()
print(b)

[  1 100   3]


Math on numpy arrays-Linear algebra

In [ ]:
import numpy as np
a=np.full((2,3),2)
print(a)

[[2 2 2]
 [2 2 2]]


Statistics

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
#np.mean(a)
#np.max(a)=6
#np.min(a)=1
#np.max(a,axis=1) #gives max of 1st row and 2nd row
np.sum(a)

21

Reorganizing arrays

In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6]])
#np.shape(a)
print(np.reshape(a,(3,2)))

[[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.vstack([a,b])

SyntaxError: ignored

In [ ]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
print(np.hstack((a,b)))

[1 2 3 4 5 6]


Loading data from a file

In [ ]:
import numpy as np
a=np.genfromtxt('temp.txt',delimiter=',')
a=a.astype(int)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18],
       [ 19,  20,  21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,
         32,  33,  34,  35,  36],
       [101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
        114, 115, 116, 117, 118]])

Boolean masking and advanced indexing

In [ ]:
import numpy as np
a=np.genfromtxt('temp.txt',delimiter=',')
a=a.astype(int)
#a[a>50] #prints elements >50
((a<50) & (a>25)) #use ~ if values except (a<50) & (a>25)

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [ ]:
#plants having supply greater than 875
plants = {'Dallas': 900, 'Las Vegas': 500, 'Detroit': 832, 'Nashville': 600, 'Los Angeles': 2400, 'Seattle': 1300, 'Denver': 1800}
x=list(plants.values())
y=list(plants.keys())
l=len(x)
i=0
updated_plants={}
for plant in plants:
  if x[i]>875:
    updated_plants[plant]=y[i]
  i=i+1
list(updated_plants.keys())

['Dallas', 'Los Angeles', 'Seattle', 'Denver']

Functions

In [ ]:
#takes in a list,returns max value
import math
def vol(r):
  volume=(4/3)*math.pi*(r)**3
  return volume
vol(2)

33.510321638291124

In [ ]:
def triangle(b,h):
  area=0.5*b*h
  return area
triangle(2,3)

3.0

Keyword arguments

In [ ]:
#converting feet to cm-function

In [ ]:
#max out of a list using function
def max(list):
  maxi=0
  x=len(list)
  for i in range(x):
    for j in range(x):
      if list[i]>=list[j]:
        maxi=list[i]
      else:
        break
  print(maxi)
#max([3,2,1])
max((3,2))

3


In [ ]:
def sing(notes):
  for note in notes:
    print("sing "+ note)
sing(['do','re','mi'])

sing do
sing re
sing mi


In [ ]:
#dictionary creator
def dictionary_creator(list1,list2):
  i=0
  if len(list1)==len(list2):
    dict={}
    for val in list1:
      dict[val]=list1[i]
      i=i+1
  else:
    print("Error")
  print(dict)
dictionary_creator(['A','B','C'],[1,2,3])

{'A': 'A', 'B': 'B', 'C': 'C'}


In [ ]:
def dictionary_creator(list1,list2):
  i=0
  j=0
  dict={}
  if len(list1)==len(list2):
    for val in list1:
      dict[val]=list1[i]
      dict[list1[i]]=list2[i]
      i=i+1
  else:
    print("Error")
  print(dict)
dictionary_creator(['x','y','z'],[20,27,15])

{'x': 20, 'y': 27, 'z': 15}


In [ ]:
!pip install PULP

     |████████████████████████████████| 14.2 MB 6.0 MB/s 


In [ ]:
from pulp import *
lp=LpProblem("Furniture",LpMaximize)
c=LpVariable("c",lowBound=0)
t=LpVariable("t",lowBound=0)
lp+=20*c+30*t #objective function
lp+=c+2*t<=100 #constraint1
lp+=2*c+t<=100 #constraint2
#lp
lp.solve()
#value(lp.objective)
#value(c)
value(t)

33.333333

In [ ]:
!pip install pulp

     |████████████████████████████████| 14.2 MB 4.4 MB/s 


In [ ]:
import pulp
i=0
costs={}
temp={}
plants=['Dallas','Los Angeles','Seattle','Denver']
supply=['Austin','Sacramento','Philadelphia','Boulder']
cost_matrix=[[2,7,4,6],
             [6,3,4,5],
             [8,4,6,5],
             [7,6,5,1]
for i in range(len(plants)):
  costs[supply[i]]
  i=i+1
costs

{'Dallas': 'Austin',
 'Denver': 'Boulder',
 'Los Angeles': 'Sacramento',
 'Seattle': 'Philadelphia'}

Pandas

In [ ]:
import pandas as pd
mydata=pd.read_csv('pokemon_data.csv',index_col='Name')
#mydata['Name'] #accessing 'Name' column
#setting column 'Name' as the index
#mydata.set_index('Name',inplace=True) #ests name as index in actual dataframe
#mydata.index #displays index 
#mydata.reset_index(inplace=True) #resetting index
#pd.set_option('display.max_rows',5) #displays only 5 rows
#pd.set_option('display.max_columns',5) #displays only 5 columns
#mydata.loc[1] #prints row 1
mydata.sort_index(ascending=False)

#  Type 1  ... Generation  Legendary
Name                                  ...                      
Zygarde50% Forme         718  Dragon  ...          6       True
Zweilous                 634    Dark  ...          5      False
...                      ...     ...  ...        ...        ...
AbomasnowMega Abomasnow  460   Grass  ...          4      False
Abomasnow                460   Grass  ...          4      False

[800 rows x 11 columns]

In [ ]:
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#data
data.set_index('Name',inplace=True)
#data.loc['Bulbasaur']
#data.iloc[2:4,:]
data.loc[['Venusaur','Bulbasaur'],'HP':'Attack']

HP  Attack
Name                 
Venusaur   80      82
Bulbasaur  45      49

In [ ]:
#filtering the dataframes
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#data
#=data.Attack>100
#x.sum()
#data.loc[x,'Attack']
mask=data.Name.apply(lambda x: x.startswith('V'))
data[mask]

#                   Name    Type 1    Type 2   HP  Attack  Defense  \
2      3               Venusaur     Grass    Poison   80      82       83   
3      3  VenusaurMega Venusaur     Grass    Poison   80     100      123   
42    37                 Vulpix      Fire       NaN   38      41       40   
50    45              Vileplume     Grass    Poison   75      80       85   
53    48                Venonat       Bug    Poison   60      55       50   
54    49               Venomoth       Bug    Poison   70      65       60   
77    71             Victreebel     Grass    Poison   80     105       65   
108  100                Voltorb  Electric       NaN   40      30       50   
145  134               Vaporeon     Water       NaN  130      65       60   
312  288               Vigoroth    Normal       NaN   80      80       80   
342  313                Volbeat       Bug       NaN   65      73       55   
360  329                Vibrava    Ground    Dragon   50      70       50   
463  416              Vespiquen       Bug    Flying   70      80      102   
553  494                Victini   Psychic      Fire  100     100      100   
603  543               Venipede       Bug    Poison   30      45       59   
643  582              Vanillite       Ice       NaN   36      50       50   
644  583              Vanillish       Ice       NaN   51      65       65   
645  584              Vanilluxe       Ice       NaN   71      95       85   
690  629                Vullaby      Dark    Flying   70      55       75   
698  637              Volcarona       Bug      Fire   85      60       65   
701  640               Virizion     Grass  Fighting   91      90       72   
734  666               Vivillon       Bug    Flying   80      52       50   
799  721              Volcanion      Fire     Water   80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
2        100      100     80           1      False  
3        122      120     80           1      False  
42        50       65     65           1      False  
50       110       90     50           1      False  
53        40       55     45           1      False  
54        90       75     90           1      False  
77       100       70     70           1      False  
108       55       55    100           1      False  
145      110       95     65           1      False  
312       55       55     90           3      False  
342       47       75     85           3      False  
360       50       50     70           3      False  
463       80      102     40           4      False  
553      100      100    100           5       True  
603       30       39     57           5      False  
643       65       60     44           5      False  
644       80       75     59           5      False  
645      110       95     79           5      False  
690       45       65     60           5      False  
698      135      105    100           5      False  
701       90      129    108           5       True  
734       90       50     89           6      False  
799      130       90     70           6       True

In [ ]:
#missing data
import pandas as pd
data=pd.read_csv('pokemon_data.csv')
#data.isna() #shows if there are any missing values in the dataframe
#data.isna().mean() #average number of missing values by percentage per column
#data.notna() #opposite of isna()
#data['Attack'].value_counts().plot(kind='bar') 
#data['Attack'].value_counts()data['Attack'].value_counts() #counts frequency of each unique entry in that column


In [ ]:
#dataframe to csv
import pandas as pd
data=pd.DataFrame({'a':[1,2],'b':[3,4]})
data
data.iloc[0,1]

3

In [ ]:
import pandas as pd
from datetime import datetime 
parser=lambda x: datetime.strptime(x,'%d-%b-%y') #%y-year as a decimal [0,99]
#%b-abbreviated month
df=pd.read_csv('zinc_prices.csv',parse_dates=['Date'],date_parser=parser)
#df['Date']=pd.to_datetime(df['Date'])
#df
#df.loc[0,'Date'].day_name() #prints the name of the day at 1-Jan-1980
#df['DayName']=df['Date'].dt.day_name() #new column DayName
#df['Date'].max()-df['Date'].min() #counts total number of days between recent and oldest dates
#df['Date']>'1990' #all the dates after 1990
filt=(df['Date']>='2019') & (df['Date']<'2020')
df.loc[filt]

Empty DataFrame
Columns: [Date, Price]
Index: []

In [ ]:
#lambda #short way to define a new function
g=lambda x: 3*x+1
g(2)

7

In [ ]:
#fullname
fullname=lambda fn,ln: fn.strip().title()+' '+ln.strip().title()
fullname('parva ','PARIKH')

'Parva Parikh'

In [ ]:
import pandas as pd
df=pd.read_csv('zinc_prices.csv')
filt=(df['Date']>='1990') & (df['Date']<'1995')
df.loc[filt]

Empty DataFrame
Columns: [Date, Price]
Index: []

In [ ]:
import pandas as pd
df=pd.read_csv('zinc_prices.csv')
df=df.dropna()
#df['Date']=pd.to_datetime(df['Date'],format='%d-%b-%Y')
#df['Date']
df['Date']=pd.to_datetime(df['Date'],format='%d-%b-%y')
#df.loc[df['Date']>'2015']
df.set_index('Date',inplace=True)
df.loc['1980']['Price'].max()  #max price for 1980
df['Price'].resample('Y').max() #max price yearly

Date
1980-12-31     868.62
1981-12-31     954.60
1982-12-31     824.53
1983-12-31     859.80
1984-12-31    1040.58
1985-12-31     930.35
1986-12-31     886.26
1987-12-31     877.44
1988-12-31    1591.74
1989-12-31    1959.91
1990-12-31    1775.00
1991-12-31    1254.00
1992-12-31    1385.41
1993-12-31    1073.63
1994-12-31    1150.27
1995-12-31    1154.81
1996-12-31    1063.25
1997-12-31    1650.63
1998-12-31    1096.25
1999-12-31    1192.93
2000-12-31    1221.67
2001-12-31    1032.70
2002-12-31     820.00
2003-12-31     976.76
2004-12-31    1182.14
2005-12-31    1819.36
2006-12-31    4381.45
2007-12-31    3847.52
2008-12-31    2511.18
2009-12-31    2374.04
2010-12-31    2414.69
2011-12-31    2473.45
2012-12-31    2057.79
2013-12-31    2128.69
2014-12-31    2326.99
2015-12-31    2281.80
2016-12-31    1709.85
Freq: A-DEC, Name: Price, dtype: float64

In [ ]:
mylist=["one",2,"three"]
print(type(mylist))
mytuple=("one",2,"three")
print(type(mytuple))

<class 'list'>
<class 'tuple'>


In [ ]:
#indexing
s="Python"
print(s[-1]) #s[5]=s[-1]=s[second last character]
len(s)

n


6

In [ ]:
#slice operator
julia=("Julia","Roberts",1967,"Duplicity",2009,"Actresses","atl,georgia")
print(julia[:3]+('Kohli','Sehwag',2011))
#julia[2]=2012 #not changeable since a tuple, could be changed if that was a list


('Julia', 'Roberts', 1967, 'Kohli', 'Sehwag', 2011)


In [ ]:
music="Pull out your music and dancing begin"
bio=["Metatarsal","Metatarsal","Fibula",[],"Tibia","Tibia",43,"Femur","Occipital","Metatarsal"]
print(music.index("m"))

14


In [ ]:
#split
intro="Hey I am Parva"
#x=intro.split() #finds spaces in string and spits the words of string to make a list
#print(x[1])
y=intro.split("ar") #splits at "ar"
print(y)

['Hey I am P', 'va']


In [ ]:
#join
x="/".join(["4","11","1999"])
print(x)

4/11/1999


In [ ]:
for name in ["Joe","Amy","Brad","Paris"]:
  print('Hi',name,'Come over to my party')

Hi Joe Come over to my party
Hi Amy Come over to my party
Hi Brad Come over to my party
Hi Paris Come over to my party


In [ ]:
for i in range(1,5):
  print(i)

1
2
3
4


In [ ]:
print(list(range(5)))

[0, 1, 2, 3, 4]


In [ ]:
#takkes in values,prints a list
len=int(input('enter list length'))
x=[]
i=0
for i in range(len):
  x.append(int(input('enter values')))
  i=i+1
print(x)

In [ ]:
#take sin a list,prints sum of all elements
len=int(input('enter list length'))
x=[]
i=0
sum=0
for i in range(len):
  x.append(int(input('enter values')))
  sum=sum+x[i]
  i=i+1
print(x)
print(sum)

enter list length3
enter values1
enter values2
enter values3
[1, 2, 3]
6
